### ISSUE TITLE
Need a way to obtain the page source for a Browser

### ISSUE THREAD

**Issue by jwilson100** [darcy-framework/darcy-web#45]
Example:

public class MyPage extends AbstractView {
     // Class data and methods

    // Something similar to the following to get the page source
    getContext().getPageSource();

|

**Comment by alechenninger** [comment]
@abocz or @dmcneil interested?

**Comment by dmcneil** [comment]
Isn't there already `Browser#getSource`?

**Comment by alechenninger** [comment]
:)
